In [2]:
import numpy as np

# a.

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# b.

In [9]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# c.

In [10]:
c = b[::-1]
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# d.

In [13]:
d = np.arange(9).reshape((3,3))
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# e.

In [15]:
e = np.array([1,2,0,0,4,0])
nonzero = np.arange(e.size)[e>0]
print(nonzero)

[0 1 4]


# f.

In [19]:
f = np.random.rand(30)
avg = f.mean()

In [20]:
print(avg)

0.4726248562289913


# g.

In [31]:
size = 7
g = np.ones((size,size))
g[1:-1,1:-1] = 0

In [32]:
print(g)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


# h.

In [52]:
odd = np.zeros(8)
odd[::2] = 1
even = np.zeros(8)
even[1::2] = 1
print(f"{odd} and {even}")

[1. 0. 1. 0. 1. 0. 1. 0.] and [0. 1. 0. 1. 0. 1. 0. 1.]


In [56]:
h = np.zeros((8,8))
h[::2] = odd
h[1::2] = even
print(h)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [57]:
#alternative

In [58]:
h = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            h[i,j] = 1
            
print(h)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# i.

In [64]:
i = np.tile([[1,0],[0,1]],(4,4))

In [65]:
print(i)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# j.

In [67]:
Z = np.arange(11)
Z[(3<Z)&(Z<8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# k.

In [3]:
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.10872108 0.14341321 0.80956689 0.85096392 0.85315892 0.86655584
 0.90186353 0.91509948 0.9345579  0.9770197 ]


# l.

In [90]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

True


# m.

In [94]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
print(Z)
Z = Z.view('float32')
print(Z.dtype)
print(Z)

int32
[0 1 2 3 4 5 6 7 8 9]
float32
[0.0e+00 1.4e-45 2.8e-45 4.2e-45 5.6e-45 7.0e-45 8.4e-45 9.8e-45 1.1e-44
 1.3e-44]


# n.

In [101]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.array([C[i,i] for i in range(3)])
D2 = np.diag(C)
print(D)
print(D2)

[ 18  66 132]
[ 18  66 132]
